name: Build and Push Web Client Image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: maftei/pocplatform-workflow-templates/.github/workflows/build-docker-image.yaml@main
    with:
      namespace: dev
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
