name: Build and Push Docker Image to ECR
#  This workflow builds a Docker image for the web client and pushes it to Amazon ECR.
on:
  push:
    branches: [main]

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: web-client

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract short Git SHA
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short=8 HEAD)" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker image
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          GIT_TAG: ${{ steps.vars.outputs.sha_short }}
        run: |
          IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY
          
          echo "Building Docker image with tag: $GIT_TAG"
          docker build -t $IMAGE_URI:$GIT_TAG .
          
          echo "Tagging also as latest"
          docker tag $IMAGE_URI:$GIT_TAG $IMAGE_URI:latest

          echo "Pushing both tags..."
          docker push $IMAGE_URI:$GIT_TAG
          docker push $IMAGE_URI:latest
